export const locations = [
  "Badegaun",
  "Bajrabarahi",
  "Balkhu",
  "Bhaisepati",
  "Bhardev",
  "Bhattedanda",
  "Bhukhel",
  "Burja Chaur",
  "Chandanpur",
  "Chhapeli",
  "Choughare",
  "Dalchoki",
  "Devichour",
  "Dhapakhel",
  "Dhungepani",
  "Ekantakuna",
  "Ghusel",
  "Godawari",
  "Gotikhel",
  "Gwarko",
  "Ikudol",
  "Kaleshowr",
  "Karyabinayak",
  "Khanikhola",
  "Khumaltar",
  "Kupondole",
  "Lagankhel",
  "Mahalaxmi",
  "Malta",
  "Manikhel",
  "Nallu",
  "Pulchowk",
  "Pyutar",
  "Radar station",
  "Sankhu",
  "Satdobato",
  "Thuladurlung",
];

export const graphData = [
  ["Pulchowk", "Ekantakuna", 1.6],
  ["Pulchowk", "Kupondole", 1.5],
  ["Lagankhel", "Satdobato", 2.1],
  ["Ekantakuna", "Satdobato", 3.2],
  ["Ekantakuna", "Balkhu", 3.8],
  ["Satdobato", "Godawari", 7.9],
  ["Pulchowk", "Lagankhel", 2.0],
  ["Satdobato", "Khumaltar", 1],
  ["Khumaltar", "Dhapakhel", 3],
  ["Karyabinayak", "Devichour", 10.2],
  ["Ekantakuna", "Bhaisepati", 2.2],
  ["Bhaisepati", "Karyabinayak", 2.6],
  ["Karyabinayak", "Bajrabarahi", 9.47],
  ["Godawari", "Badegaun", 2.3],
  ["Badegaun", "Bajrabarahi", 3.2],
  ["Bajrabarahi", "Devichour", 11.2],
  ["Devichour", "Ghusel", 6.7],
  ["Ghusel", "Radar station", 6.1],
  ["Radar station", "Burja Chaur", 3.5],
  ["Burja Chaur", "Dhungepani", 3.7],
  ["Dhungepani", "Malta", 7], // No direct road available to reach Malta from Ghusel.
  ["Bhattedanda", "Malta", 11.3],
  ["Malta", "Khanikhola", 10.1],
  ["Khanikhola", "Pyutar", 5.8],
  ["Chhappeli", "Bhattedanda", 5.2],
  ["Pyutar", "Chhapeli", 9.1],
  ["Pyutar", "Ikudol", 11],
  ["Ikudol", "Sankhu", 12],
  ["Ikudol", "Bhukhel", 13],
  ["Bhattedanda", "Sankhu", 8.5],
  ["Sankhu", "Bukhel", 11.8],
  ["Sankhu", "Dalchoki", 11.6],
  ["Sankhu", "Choughare", 7.7],
  ["Bukhel", "Manikhel", 10],
  ["Manikhel", "Gotikhel", 13.5],
  ["Manikhel", "Choughare", 13],
  ["Choughare", "Bhardev", 11.9],
  ["Gotikhel", "Chandanpur", 13.2],
  ["Gotikhel", "Kaleshowr", 14],
  ["Gotikhel", "Thuladurlung", 13],
  ["Thuladurlung", "Chandanpur", 13],
  ["Chandanpur", "Kaleshowr", 16],
  ["Manikhel", "Kaleshowr", 14],
  ["Manikhel", "Bhardev", 11.9],
  ["Bhardev", "Nallu", 5.1],
  ["Nallu", "Dalchoki", 6.8],
  ["Nallu", "Bajrabarahi", 12.5],
  ["Bhardev", "Godawari", 17.1],
  ["Godawari", "Mahalaxmi", 8.6],
  ["Mahalaxmi", "Gwarko", 5.6],
  ["Gwarko", "Lagankhel", 1.4],
];
